project:
  type: website
  output-dir: docs

website:
  title: "miniproject3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text_analysis.qmd

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: visual

