---
title: "Choropleth Maps"
toc: false
about:
  template: jolla
  links:
    - text: GitHub
      href: https://github.com/philli17/miniproject3/blob/main/maps.qmd
    - text: Data
      href: https://data.census.gov/table/ACSST1Y2024.S0101?g=010XX00US$0400000
---


```{r}
#| message: false
#| warning: false
#| echo: false

library(tidyr)
library(dplyr)
library(readr)
library(tidyverse)
library(mdsr)
library(maps)
library(viridis)
library(lubridate)
library(statebins)
library(leaflet)

census <- read_csv("Census.csv")

us_states <- map_data("state")
```

Using data from the US Census (data.census.gov), I was curious about mapping the different age categories of Americans. For example, the map below is of children under age 5. The percentages are for that state, so 5.5% of the total population of Alabama is children under age 5.

```{r}
#| echo: false
#this is the percent under 5 static map
census_age <- census |>
  select(-ends_with("Male!!Estimate")) |>
  select(-ends_with("Female!!Estimate")) |>
  slice_head(n = 20)
census_age <- census_age[-2, ]
percent_5 <- census_age[2, ]
percent_5 <- percent_5 |>
  select(-ends_with("Total!!Estimate"))
percent_5 <- percent_5 |>
  pivot_longer(
    cols = !`Label (Grouping)`,
    names_to = "state",
    values_to = "percent"
  )
percent_5 <- percent_5 |>
  mutate(state = str_extract(state, "[A-Za-z\\s]*[^!]"))

percent_5 <- percent_5 |>
  mutate(state = str_to_lower(state))

percent_5 |>
  right_join(us_states, by = c("state" = "region")) |>
  rename(region = state) |>
  ggplot(mapping = aes(x = long, y = lat,
                          group = group)) + 
  geom_polygon(aes(fill = percent), color = "black")
```

```{r}
#| echo: false
#this chunk makes the population totals for male/female by state
census_sex <- census |>
  select(-ends_with("Total!!Estimate")) |>
  select(-ends_with("Percent!!Estimate")) |>
  select(-ends_with(" Male!!Estimate")) |>
  select(-ends_with(" Female!!Estimate")) |>
  slice_head(n = 20) 
census_sex <- census_sex[-1, ]
census_sex <- census_sex[-1, ]
census_sex <- census_sex |>
  mutate(across(everything(), parse_number))
  census_sex <- rbind(census_sex, c("Total", colSums(census_sex[,2:105])))
  census_sex <- census_sex[19, ]

census_sex <- census_sex |>
  pivot_longer(
    cols = !`Label (Grouping)`,
    names_to = "state",
    values_to = "number"
  )

census_sex <- census_sex |>
  mutate(sex = str_detect(state, "Male")) |>
  mutate(sex = ifelse(sex == TRUE, "Male", "Female"))

census_sex <- census_sex |>
  mutate(state = str_extract(state, "[A-Za-z\\s]*[^!]"))

census_sex <- census_sex |>
  mutate(state = str_to_lower(state))

census_sex <- census_sex |>
  pivot_wider(
    names_from = sex,
    values_from = number
  )

census_sex <- census_sex |>
  mutate(greater = case_when (
    Male > Female ~ "M",
    Female > Male ~ "F"
  ))
```


```{r}
#| echo: false
census_sex |>
  right_join(us_states, by = c("state" = "region")) |>
  rename(region = state) |>
  ggplot(mapping = aes(x = long, y = lat,
                          group = group)) + 
  geom_polygon(aes(fill = greater), color = "black")
```
